### ISSUE TITLE
ardulink-core-mqtt prevents resolving dependencies

### ISSUE THREAD

**Issue by fantasticfears** [Ardulink/Ardulink-2#1]
I am looking forward to compare several serial communication protocol for Arduino. Ardulink2 looks promising to me. 

But I found `ardulink-core-mqtt` is preventing the building.

I use Intellij IDEA 2016.1.1. Removing several related packages with it can make it possible to run. But I suppose there is a problem which I don't understand.

I attempted to put a bintray https url, took a partial snippet from bintray website and updating to the latest 0.7 for moquette-broker. Though none of those can work :(

https://bintray.com/andsel/maven/org.dna.mqtt.moquette-broker/view

**Comment by pfichtner** [comment]
What type of error do you get? Can you paste a snippet somewhere? 
A quickfix could be to purge the ardulink-core-mqtt from the parent pom.

**Comment by fantasticfears** [comment]
I clear builds by `clean`. And another dependency issue comes up..

I ran the `compile` on parent:

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java "-Dmaven.home=/opt/homebrew-cask/Caskroom/intellij-idea/2016.1.1/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3" "-Dclassworlds.conf=/opt/homebrew-cask/Caskroom/intellij-idea/2016.1.1/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/bin/m2.conf" -Didea.launcher.port=7534 "-Didea.launcher.bin.path=/opt/homebrew-cask/Caskroom/intellij-idea/2016.1.1/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/opt/homebrew-cask/Caskroom/intellij-idea/2016.1.1/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.4.jar:/opt/homebrew-cask/Caskroom/intellij-idea/2016.1.1/IntelliJ IDEA.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain org.codehaus.classworlds.Launcher -Didea.version=2016.1.1 --update-snapshots compile
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] parent
[INFO] ardulink-core-util
[INFO] ardulink-core-beans
[INFO] ardulink-core-base
[INFO] ardulink-core-serial-rxtx
[INFO] ardulink-core-bluetooth
[INFO] ardulink-core-digispark
[INFO] ardulink-core-raspberry
[INFO] ardulink-core-proxy
[INFO] ardulink-core-mqtt
[INFO] ardulink-legacy
[INFO] ardulink-networkproxyserver
[INFO] ardulink-mqtt
[INFO] ardulink-swing
[INFO] ardulink-console
[INFO] ardulink-mail
[INFO] example-datareceiver
[INFO] example-joysticksmartcardriver
[INFO] example-simplesmartcardriver
[INFO] deploy-dist
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building parent 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ardulink-core-util 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ ardulink-core-util ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/fantasticfears/Dev/Ardulink-2/ardulink-core-util/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ ardulink-core-util ---
[INFO] Nothing to compile - all classes are up to date
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ardulink-core-beans 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ ardulink-core-beans ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/fantasticfears/Dev/Ardulink-2/ardulink-core-beans/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ ardulink-core-beans ---
[INFO] Nothing to compile - all classes are up to date
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ardulink-core-base 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ ardulink-core-base ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ ardulink-core-base ---
[INFO] Nothing to compile - all classes are up to date
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ardulink-core-serial-rxtx 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ ardulink-core-serial-rxtx ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ ardulink-core-serial-rxtx ---
[INFO] Nothing to compile - all classes are up to date
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ardulink-core-bluetooth 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: file:///Users/fantasticfears/Dev/Ardulink-2/ardulink-core-bluetooth/../local-repo/net/sf/bluecove/bluecove/2.1.1-SNAPSHOT/maven-metadata.xml
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ ardulink-core-bluetooth ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ ardulink-core-bluetooth ---
[INFO] Compiling 2 source files to /Users/fantasticfears/Dev/Ardulink-2/ardulink-core-bluetooth/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/fantasticfears/Dev/Ardulink-2/ardulink-core-bluetooth/src/main/java/org/ardulink/core/bluetooth/BluetoothLinkConfig.java:[51,39] error: cannot find symbol
[ERROR]  class BluetoothLinkConfig
/Users/fantasticfears/Dev/Ardulink-2/ardulink-core-bluetooth/src/main/java/org/ardulink/core/bluetooth/BluetoothLinkFactory.java:[83,32] error: cannot find symbol
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] parent ............................................ SUCCESS [0.002s]
[INFO] ardulink-core-util ................................ SUCCESS [0.646s]
[INFO] ardulink-core-beans ............................... SUCCESS [0.036s]
[INFO] ardulink-core-base ................................ SUCCESS [0.117s]
[INFO] ardulink-core-serial-rxtx ......................... SUCCESS [0.053s]
[INFO] ardulink-core-bluetooth ........................... FAILURE [0.882s]
[INFO] ardulink-core-digispark ........................... SKIPPED
[INFO] ardulink-core-raspberry ........................... SKIPPED
[INFO] ardulink-core-proxy ............................... SKIPPED
[INFO] ardulink-core-mqtt ................................ SKIPPED
[INFO] ardulink-legacy ................................... SKIPPED
[INFO] ardulink-networkproxyserver ....................... SKIPPED
[INFO] ardulink-mqtt ..................................... SKIPPED
[INFO] ardulink-swing .................................... SKIPPED
[INFO] ardulink-console .................................. SKIPPED
[INFO] ardulink-mail ..................................... SKIPPED
[INFO] example-datareceiver .............................. SKIPPED
[INFO] example-joysticksmartcardriver .................... SKIPPED
[INFO] example-simplesmartcardriver ...................... SKIPPED
[INFO] deploy-dist ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.021s
[INFO] Finished at: Thu Apr 28 09:28:36 CEST 2016
[INFO] Final Memory: 12M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project ardulink-core-bluetooth: Compilation failure: Compilation failure:
[ERROR] /Users/fantasticfears/Dev/Ardulink-2/ardulink-core-bluetooth/src/main/java/org/ardulink/core/bluetooth/BluetoothLinkConfig.java:[51,39] error: cannot find symbol
[ERROR] class BluetoothLinkConfig
[ERROR] /Users/fantasticfears/Dev/Ardulink-2/ardulink-core-bluetooth/src/main/java/org/ardulink/core/bluetooth/BluetoothLinkFactory.java:[83,32] error: cannot find symbol
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ardulink-core-bluetooth

Process finished with exit code 1
```

----

For ardulink-core-mqtt:

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java "-Dmaven.home=/opt/homebrew-cask/Caskroom/intellij-idea/2016.1.1/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3" "-Dclassworlds.conf=/opt/homebrew-cask/Caskroom/intellij-idea/2016.1.1/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/bin/m2.conf" -Didea.launcher.port=7536 "-Didea.launcher.bin.path=/opt/homebrew-cask/Caskroom/intellij-idea/2016.1.1/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/opt/homebrew-cask/Caskroom/intellij-idea/2016.1.1/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.4.jar:/opt/homebrew-cask/Caskroom/intellij-idea/2016.1.1/IntelliJ IDEA.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain org.codehaus.classworlds.Launcher -Didea.version=2016.1.1 compile -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ardulink-core-mqtt 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.ardulink:ardulink-core-base:jar:2.0.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.687s
[INFO] Finished at: Thu Apr 28 09:31:11 CEST 2016
[INFO] Final Memory: 5M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ardulink-core-mqtt: Could not resolve dependencies for project org.ardulink:ardulink-core-mqtt:jar:2.0.0-SNAPSHOT: Failed to collect dependencies for [org.ardulink:ardulink-core-base:jar:2.0.0-SNAPSHOT (compile), org.slf4j:slf4j-api:jar:1.7.12 (compile), org.slf4j:slf4j-jdk14:jar:1.7.12 (runtime), javax.validation:validation-api:jar:1.0.0.GA (compile), org.fusesource.mqtt-client:mqtt-client:jar:1.11 (compile), junit:junit:jar:4.12 (test), org.dna.mqtt:moquette-broker:jar:0.6 (test)]: Failed to read artifact descriptor for org.dna.mqtt:moquette-broker:jar:0.6: Failure to find org.dna.mqtt:moquette-parent:pom:0.6 in http://dl.bintray.com/andsel/maven/ was cached in the local repository, resolution will not be reattempted until the update interval of bintray has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project ardulink-core-mqtt: Could not resolve dependencies for project org.ardulink:ardulink-core-mqtt:jar:2.0.0-SNAPSHOT: Failed to collect dependencies for [org.ardulink:ardulink-core-base:jar:2.0.0-SNAPSHOT (compile), org.slf4j:slf4j-api:jar:1.7.12 (compile), org.slf4j:slf4j-jdk14:jar:1.7.12 (runtime), javax.validation:validation-api:jar:1.0.0.GA (compile), org.fusesource.mqtt-client:mqtt-client:jar:1.11 (compile), junit:junit:jar:4.12 (test), org.dna.mqtt:moquette-broker:jar:0.6 (test)]
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:210)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:117)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:258)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:201)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.ardulink:ardulink-core-mqtt:jar:2.0.0-SNAPSHOT: Failed to collect dependencies for [org.ardulink:ardulink-core-base:jar:2.0.0-SNAPSHOT (compile), org.slf4j:slf4j-api:jar:1.7.12 (compile), org.slf4j:slf4j-jdk14:jar:1.7.12 (runtime), javax.validation:validation-api:jar:1.0.0.GA (compile), org.fusesource.mqtt-client:mqtt-client:jar:1.11 (compile), junit:junit:jar:4.12 (test), org.dna.mqtt:moquette-broker:jar:0.6 (test)]
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:158)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:185)
	... 28 more
Caused by: org.sonatype.aether.collection.DependencyCollectionException: Failed to collect dependencies for [org.ardulink:ardulink-core-base:jar:2.0.0-SNAPSHOT (compile), org.slf4j:slf4j-api:jar:1.7.12 (compile), org.slf4j:slf4j-jdk14:jar:1.7.12 (runtime), javax.validation:validation-api:jar:1.0.0.GA (compile), org.fusesource.mqtt-client:mqtt-client:jar:1.11 (compile), junit:junit:jar:4.12 (test), org.dna.mqtt:moquette-broker:jar:0.6 (test)]
	at org.sonatype.aether.impl.internal.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:258)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:308)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:150)
	... 29 more
Caused by: org.sonatype.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.dna.mqtt:moquette-broker:jar:0.6
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:331)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:186)
	at org.sonatype.aether.impl.internal.DefaultDependencyCollector.process(DefaultDependencyCollector.java:412)
	at org.sonatype.aether.impl.internal.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:240)
	... 31 more
Caused by: org.apache.maven.model.resolution.UnresolvableModelException: Failure to find org.dna.mqtt:moquette-parent:pom:0.6 in http://dl.bintray.com/andsel/maven/ was cached in the local repository, resolution will not be reattempted until the update interval of bintray has elapsed or updates are forced
	at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:126)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:813)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:664)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:310)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:232)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:322)
	... 34 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Failure to find org.dna.mqtt:moquette-parent:pom:0.6 in http://dl.bintray.com/andsel/maven/ was cached in the local repository, resolution will not be reattempted until the update interval of bintray has elapsed or updates are forced
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:193)
	at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:122)
	... 39 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Failure to find org.dna.mqtt:moquette-parent:pom:0.6 in http://dl.bintray.com/andsel/maven/ was cached in the local repository, resolution will not be reattempted until the update interval of bintray has elapsed or updates are forced
	at org.sonatype.aether.impl.internal.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:230)
	at org.sonatype.aether.impl.internal.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:204)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:427)
	... 42 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Process finished with exit code 1
```

----

I guess the purge is `dependency:purge-local-repository`. It did success on parent but takes no effect.

Related Maven settings:

![image](https://cloud.githubusercontent.com/assets/297343/14878498/379cb896-0d24-11e6-85b6-5df30a2820d2.png)

**Comment by pfichtner** [comment]
On a fresh checkout I got the same errors. @LucianoZu could you please fix them?

**Comment by LucianoZu** [comment]
Ok I'll see it asap
Il 30 apr 2016 9:53 AM, "Peter Fichtner" <notifications@github.com> ha
scritto:

**Comment by LucianoZu** [comment]
Now it should be fixed. The problem I encountered was on MQTT for a JAR used in tests (moquette). Bluetooth compiles like a charms. Maybe some push solved the issue on bluetooth.

Now Travis CI is up and running.

**Comment by LucianoZu** [comment]
If you agree please close this issue

**Comment by fantasticfears** [comment]
It works perfectly on my end. Thanks!
